version: '3.9'
services:
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda start --overprovisioned --smp 1 --memory 512M --reserve-memory 0M \
        --node-id 0 --check=false --kafka-addr PLAINTEXT://0.0.0.0:9092 \
        --advertise-kafka-addr PLAINTEXT://redpanda:9092
    ports:
      - '9092:9092'

  postgres:
    image: postgres:15
    container_name: pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: etl
    ports:
      - '5432:5432'

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
